######### Cadastro de Mensagem
POST http://127.0.0.1:3333/messages HTTP/1.1 
Content-Type: application/json 
Authorization: Bearer MQ.MDJJNzA9veUo3rfJ1R3LDymxkZUrjtBzF60J1qhPIgmHOG7Gl7jBH2kCnW0d

{
    "title": "Olá", 
    "message": "Segunda mensagem do chat!"
}

######### Listar todos as Mensagens
GET http://127.0.0.1:3333/messages HTTP/1.1 
Content-Type: application/json 
Authorization: Bearer MQ.MDJJNzA9veUo3rfJ1R3LDymxkZUrjtBzF60J1qhPIgmHOG7Gl7jBH2kCnW0d
######### Listar Mensagem específica 
GET http://127.0.0.1:3333/messages/1 HTTP/1.1 
Content-Type: application/json 
Authorization: Bearer MQ.MDJJNzA9veUo3rfJ1R3LDymxkZUrjtBzF60J1qhPIgmHOG7Gl7jBH2kCnW0d

######### Alterar Mensagem 
PUT http://127.0.0.1:3333/messages/1 HTTP/1.1 
Content-Type: application/json 
Authorization: Bearer MQ.MDJJNzA9veUo3rfJ1R3LDymxkZUrjtBzF60J1qhPIgmHOG7Gl7jBH2kCnW0d
{
    "title": "Olá", 
    "message": "Mensagem do chat alterada!"
}

######### Apagar Mensagem 
DELETE http://127.0.0.1:3333/messages/1 HTTP/1.1 
Content-Type: application/json 
Authorization: Bearer MQ.MDJJNzA9veUo3rfJ1R3LDymxkZUrjtBzF60J1qhPIgmHOG7Gl7jBH2kCnW0d