######### Cadastro Tópico
POST http://127.0.0.1:3333/topics HTTP/1.1
Content-Type: application/json
Authorization: Bearer Mg.1FP7y5f_vMRLsPUw2ieNQumE0d3AVSgkUIl3jcrugTk2N3PIpj-3U_yba3Mo

{
    "name": "Recomendados"
}

######### Listar todos os Tópico
GET http://127.0.0.1:3333/topics HTTP/1.1
Content-Type: application/json
Authorization: Bearer Mg.1FP7y5f_vMRLsPUw2ieNQumE0d3AVSgkUIl3jcrugTk2N3PIpj-3U_yba3Mo


######### Listar Tópico específico
GET http://127.0.0.1:3333/topics/1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer Mg.1FP7y5f_vMRLsPUw2ieNQumE0d3AVSgkUIl3jcrugTk2N3PIpj-3U_yba3Mo

######### Alterar Tópico
PUT http://127.0.0.1:3333/topics/1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer Mg.1FP7y5f_vMRLsPUw2ieNQumE0d3AVSgkUIl3jcrugTk2N3PIpj-3U_yba3Mo

{
    "name": "Recomendados"
}

######### Apagar Tópico
DELETE http://127.0.0.1:3333/topics/1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer Mg.1FP7y5f_vMRLsPUw2ieNQumE0d3AVSgkUIl3jcrugTk2N3PIpj-3U_yba3Mo

