######### Cadastro Tópico
POST http://127.0.0.1:3333/topics HTTP/1.1
Content-Type: application/json
Authorization: Bearer Mw.ZaeH3uoEburAmw_XkKYPTQhdlpDoVFq8BRUVvScl7h6fezwlPhuE-2aVhM8z

{
    "name": "Recomendados"
}

######### Listar todos os Tópico
GET http://127.0.0.1:3333/topics HTTP/1.1
Content-Type: application/json
Authorization: Bearer Mw.ZaeH3uoEburAmw_XkKYPTQhdlpDoVFq8BRUVvScl7h6fezwlPhuE-2aVhM8z


######### Listar Tópico específico
GET http://127.0.0.1:3333/topics/1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer Mw.ZaeH3uoEburAmw_XkKYPTQhdlpDoVFq8BRUVvScl7h6fezwlPhuE-2aVhM8z

######### Alterar Tópico
PUT http://127.0.0.1:3333/topics/1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer Mw.ZaeH3uoEburAmw_XkKYPTQhdlpDoVFq8BRUVvScl7h6fezwlPhuE-2aVhM8z

{
    "name": "Recomendados"
}

######### Apagar Tópico
DELETE http://127.0.0.1:3333/topics/1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer Mw.ZaeH3uoEburAmw_XkKYPTQhdlpDoVFq8BRUVvScl7h6fezwlPhuE-2aVhM8z

